---
abstract: 'Perl wrapper for Technical Analysis Library'
author:
  - 'Wim Verhaegen <wimv@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-TA
no_index:
  directory:
    - t
    - inc
    - _swig
requires:
  Test: 0
resources:
  homepage: http://ta-lib.org/
  repository: https://github.com/kmx/perl-finance-ta
version: v0.4.1
